### PR TITLE
Prevents AA from going 737 MAX when a typo is entered on the GUI's text entries

### PR DESCRIPTION
**Pull request by Lisias**
There's a nasty usability bug on the NeoGUI: if the user mistypes something (as entering a letter, or switching the `.` with a `,`, as it's usual on PT-BR keyboards), AA end up getting a completely screwed value on the field - with very nasty consequences.

> As a matter of fact, this just happened today while programming my ascent - and since I use the GPWS add'on, it happened with that terrifying "PULL UP" warning.
>
> Really, really spine freezing event.

To prevent this problem, I reworked the text input to reset to the previous valid value if en error is detected while parsing the input.

It appears to work fine until the moment - I'm currently testing the thing again (it's some time since I coded it, but I ended up forgetting to do the pull request)

### CODE REVIEW

**Comment by Lisias** [comment]
FYI: the code is running fine until this moment on my rigs, I'm currently code reviewing it with someone that knows this code better in order to see if there's how to improve this.

I will come back to you as soon as I finish the mentioned review.

**Comment by Boris-Barboris** [comment]
Hi, thanks! I'll have a look this week.

**Review by Hotel26 — APPROVED** [review]
Looks fine.  (Thanks for preserving the dms format parsing.)  I haven't built and tested as that will involve some archaeology first, but am willing to test your plugin, if you care to put it on e.g. DropBox or Drive.

(It looks like there might be some preprocessor in play?  I wasn't familiar with the \<#= syntax.  I see the file extension is ".ttinclude".  That should give me a hook to find out something about it.  github:mono/t4?)

**Comment by Boris-Barboris** [comment]
LGTM

**Comment by Lisias** [comment]
I'm flagging this as ready for review/merge as I'm using this for more than a week now and it (still) works. No more crashes due letters or commas being accidentally inputted! :)

**Comment by Lisias** [comment]
> (It looks like there might be some preprocessor in play? I wasn't familiar with the <#= syntax. I see the file extension is ".ttinclude". That should give me a hook to find out something about it. github:mono/t4?)

Yes, and I fixed the preprocessor thingy - but it's not exactly needed all the time, because the generated CS file is also committed (and this is the reason it went broken for so much time).

The NeoGUI, however, appears to succeed the DelayedField thingy, ideally we should migrate the code to be used on NeoGUI and remove it - but I think this is a fight for another day.

**Comment by Lisias** [comment]
@Hotel26 

> Looks fine. (Thanks for preserving the dms format parsing.)

It was there for a reason, so I preserved it! :) 


> I haven't built and tested as that will involve some archaeology first, but am willing to test your plugin, if you care to put it on e.g. DropBox or Drive.

Here, I compiled a custom DLL for you. Install AA, then replace the original DLLs with the ones from the file below. It was compiled against KSP 1.8.0 and should work fine from it to the latest. For the sake of curiosity, I have a custom DLL that works fine from 1.4.0 to 1.12.5 (and I think it will work too on KSP 1.3.1, but didn't had the time to test it yet).

[AtmosphereAutopilot.custom.lisias.zip](https://github.com/Boris-Barboris/AtmosphereAutopilot/files/11815944/AtmosphereAutopilot.custom.lisias.zip)

**Pull request merged**
